"""Add alarm_record model

Revision ID: 14ad5ad0f3eb
Revises: 9ba8046abcd2
Create Date: 2026-02-09 13:58:04.614180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ad5ad0f3eb'
down_revision = '9ba8046abcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='报警时间'),
    sa.Column('alarm_type', sa.String(length=50), nullable=False, comment='报警类型(矿压/微震/变形/压裂)'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='报警级别(RED/YELLOW)'),
    sa.Column('value', sa.Float(), nullable=True, comment='触发值'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='设定的阈值'),
    sa.Column('message', sa.Text(), nullable=True, comment='报警描述'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='处理状态(PENDING/ACKNOWLEDGED/CLEARED)'),
    sa.Column('handler_remark', sa.Text(), nullable=True, comment='处理意见'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alarm_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alarm_record_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alarm_record_timestamp'))

    op.drop_table('alarm_record')
    # ### end Alembic commands ###
