"""Add role to user

Revision ID: 310fe2a8b5ee
Revises: 14ad5ad0f3eb
Create Date: 2026-02-09 15:24:28.566897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310fe2a8b5ee'
down_revision = '14ad5ad0f3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True, comment='角色(ADMIN/USER)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
