"""initial migration

Revision ID: 791d7cb33f93
Revises: 
Create Date: 2026-02-02 21:35:59.173929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d7cb33f93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drilling_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='钻场名称'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='位置'),
    sa.Column('coord_e', sa.Float(), nullable=True, comment='大地坐标东坐标'),
    sa.Column('coord_n', sa.Float(), nullable=True, comment='大地坐标北坐标'),
    sa.Column('coord_z', sa.Float(), nullable=True, comment='巷道标高'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microseismic_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True, comment='事件时间'),
    sa.Column('coord_x', sa.Float(), nullable=True, comment='X坐标'),
    sa.Column('coord_y', sa.Float(), nullable=True, comment='Y坐标'),
    sa.Column('coord_z', sa.Float(), nullable=True, comment='Z坐标'),
    sa.Column('energy', sa.Float(), nullable=True, comment='能量(J)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('microseismic_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_microseismic_event_event_time'), ['event_time'], unique=False)

    op.create_table('roadway_deformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.Column('station_id', sa.String(length=100), nullable=True, comment='测站ID'),
    sa.Column('top_bottom_deformation', sa.Float(), nullable=True, comment='顶底板变形量(mm)'),
    sa.Column('left_right_deformation', sa.Float(), nullable=True, comment='两帮变形量(mm)'),
    sa.Column('deformation_rate', sa.Float(), nullable=True, comment='变形速率(mm/d)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadway_deformation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadway_deformation_record_time'), ['record_time'], unique=False)

    op.create_table('support_pressure_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.Column('station_no', sa.Integer(), nullable=True, comment='测站号'),
    sa.Column('support_no', sa.Integer(), nullable=True, comment='支架号'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='位置'),
    sa.Column('p1', sa.Float(), nullable=True, comment='压力P1(MPa)'),
    sa.Column('p2', sa.Float(), nullable=True, comment='压力P2(MPa)'),
    sa.Column('p3', sa.Float(), nullable=True, comment='压力P3(MPa)'),
    sa.Column('angle_x', sa.Float(), nullable=True, comment='X方向角度'),
    sa.Column('angle_y', sa.Float(), nullable=True, comment='Y方向角度'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_pressure_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_pressure_data_record_time'), ['record_time'], unique=False)

    op.create_table('borehole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drilling_site_id', sa.Integer(), nullable=False, comment='所属钻场ID'),
    sa.Column('borehole_no', sa.String(length=50), nullable=False, comment='钻孔编号'),
    sa.Column('diameter', sa.Float(), nullable=True, comment='孔径(mm)'),
    sa.Column('design_length', sa.Float(), nullable=True, comment='设计长度(m)'),
    sa.Column('azimuth', sa.Float(), nullable=True, comment='设计方位角'),
    sa.Column('dip_angle', sa.Float(), nullable=True, comment='设计倾角'),
    sa.Column('segments', sa.Integer(), nullable=True, comment='计划压裂段数'),
    sa.ForeignKeyConstraint(['drilling_site_id'], ['drilling_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borehole_trajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=False, comment='所属钻孔ID'),
    sa.Column('measured_depth', sa.Float(), nullable=False, comment='测深(m)'),
    sa.Column('dip_angle', sa.Float(), nullable=True, comment='倾角'),
    sa.Column('grid_azimuth', sa.Float(), nullable=True, comment='方位角'),
    sa.Column('coord_e', sa.Float(), nullable=True, comment='坐标E'),
    sa.Column('coord_n', sa.Float(), nullable=True, comment='坐标N'),
    sa.Column('coord_z', sa.Float(), nullable=True, comment='坐标Z'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='测量时间'),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borehole_trajectory')
    op.drop_table('borehole')
    with op.batch_alter_table('support_pressure_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_pressure_data_record_time'))

    op.drop_table('support_pressure_data')
    with op.batch_alter_table('roadway_deformation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadway_deformation_record_time'))

    op.drop_table('roadway_deformation')
    with op.batch_alter_table('microseismic_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_microseismic_event_event_time'))

    op.drop_table('microseismic_event')
    op.drop_table('drilling_site')
    # ### end Alembic commands ###
