"""Add fracture and log models

Revision ID: 9ba8046abcd2
Revises: b03a2ce09b72
Create Date: 2026-02-09 12:14:21.178040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba8046abcd2'
down_revision = 'b03a2ce09b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='日志时间'),
    sa.Column('interface_name', sa.String(length=100), nullable=False, comment='接口名称/来源'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态(SUCCESS/ERROR)'),
    sa.Column('message', sa.Text(), nullable=True, comment='详细消息'),
    sa.Column('payload', sa.Text(), nullable=True, comment='原始数据载荷(可选)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interface_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interface_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('fracture_construction_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.Column('borehole_id', sa.Integer(), nullable=False, comment='所属钻孔ID'),
    sa.Column('segment_no', sa.Integer(), nullable=True, comment='压裂段号'),
    sa.Column('pressure', sa.Float(), nullable=True, comment='施工压力(MPa)'),
    sa.Column('flow_rate', sa.Float(), nullable=True, comment='瞬时流量(m3/min)'),
    sa.Column('total_volume', sa.Float(), nullable=True, comment='累计排量(m3)'),
    sa.Column('sand_concentration', sa.Float(), nullable=True, comment='砂浓度(kg/m3)'),
    sa.ForeignKeyConstraint(['borehole_id'], ['borehole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fracture_construction_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fracture_construction_data_record_time'), ['record_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fracture_construction_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fracture_construction_data_record_time'))

    op.drop_table('fracture_construction_data')
    with op.batch_alter_table('interface_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interface_log_timestamp'))

    op.drop_table('interface_log')
    # ### end Alembic commands ###
