"""add working_face and monitoring_station models

Revision ID: e936f02a3a7a
Revises: a65ede6873c4
Create Date: 2026-02-12 22:54:55.952639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e936f02a3a7a'
down_revision = 'a65ede6873c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False, comment='测点编号/ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='测点类型(矿压/微震/变形)'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='安装位置'),
    sa.Column('coord_x', sa.Float(), nullable=True, comment='X坐标'),
    sa.Column('coord_y', sa.Float(), nullable=True, comment='Y坐标'),
    sa.Column('coord_z', sa.Float(), nullable=True, comment='Z坐标'),
    sa.Column('install_date', sa.DateTime(), nullable=True, comment='安装日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态(ACTIVE/INACTIVE)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('working_face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工作面名称'),
    sa.Column('length', sa.Float(), nullable=True, comment='工作面长度(m)'),
    sa.Column('advance_length', sa.Float(), nullable=True, comment='推进长度(m)'),
    sa.Column('mining_height', sa.Float(), nullable=True, comment='采高(m)'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='开采日期'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('drilling_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_face_id', sa.Integer(), nullable=True, comment='所属工作面ID'))
        batch_op.create_foreign_key(None, 'working_face', ['working_face_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drilling_site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('working_face_id')

    op.drop_table('working_face')
    op.drop_table('monitoring_station')
    # ### end Alembic commands ###
